name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 17, 18 ]
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      # delete gradle.properties in Java 8 because it contains a then-unsupported JVM argument: --add-exports
      - run: rm gradle.properties
        if: ${{ matrix.java-version == 8 }}

      - run: ./gradlew assemble check --info
